### ISSUE TITLE
Comentarios avance 1

### ISSUE THREAD

**Issue by AliciaMstt** [yolitzi/ProyectoFinalBioinf2018-II#1]
Se ve interesante y creo que tendrás todos los datos que necesitas para el proyecto. Respecto al posible cambio, esá bien, siempre y cuando no sea demasiado tarde para que no te coman los tiempos. Avísanos por este medio y en el avance 2 qué pasa al respecto.

**Comment by yolitzi** [comment]
Sí voy a hacer el análisis de metiloma, así que seguiré con estos datos para el avance 2 y el proyecto final :).
